// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/streadway/amqp"
	"go.mongodb.org/mongo-driver/mongo"
	"pixstall-artist/app/artist/delivery/http"
	"pixstall-artist/app/artist/delivery/rabbitmq"
	mongo2 "pixstall-artist/app/artist/repo/mongo"
	"pixstall-artist/app/artist/usecase"
)

// Injectors from wire.go:

func InitArtistController(db *mongo.Database) http.ArtistController {
	repo := mongo2.NewMongoArtistRepo(db)
	useCase := usecase.NewArtistUseCase(repo)
	artistController := http.NewArtistController(useCase)
	return artistController
}

func InitArtistMessageBroker(db *mongo.Database, conn *amqp.Connection) rabbitmq.ArtistMessageBroker {
	repo := mongo2.NewMongoArtistRepo(db)
	useCase := usecase.NewArtistUseCase(repo)
	artistMessageBroker := rabbitmq.NewRabbitMQArtistMessageBroker(useCase, conn)
	return artistMessageBroker
}
